export enum ConversationState {
  IDLE = 'IDLE',
  MAIN_MENU = 'MAIN_MENU',

  // Registration flow
  REGISTRATION_NAME = 'REGISTRATION_NAME',
  REGISTRATION_PHONE = 'REGISTRATION_PHONE',
  REGISTRATION_EMAIL = 'REGISTRATION_EMAIL',
  REGISTRATION_REGION = 'REGISTRATION_REGION',
  REGISTRATION_KVIC = 'REGISTRATION_KVIC',
  REGISTRATION_CONFIRM = 'REGISTRATION_CONFIRM',

  // Disease detection flow
  DISEASE_AWAITING_IMAGE = 'DISEASE_AWAITING_IMAGE',
  DISEASE_PROCESSING = 'DISEASE_PROCESSING',

  // Hive status flow
  HIVE_STATUS = 'HIVE_STATUS',
  HIVE_SELECT = 'HIVE_SELECT',

  // Batch status flow
  BATCH_STATUS_AWAITING_ID = 'BATCH_STATUS_AWAITING_ID',

  // Health report flow
  HEALTH_REPORT = 'HEALTH_REPORT',

  // Language
  LANGUAGE_SELECT = 'LANGUAGE_SELECT',
}
